# Generated by Django 5.2.6 on 2025-11-12 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('biografia', models.TextField(help_text='Breve biografía del autor', verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Autor activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(choices=[('REG', 'Regular'), ('VIP', 'VIP'), ('EMP', 'Empresarial')], default='REG', max_length=3, verbose_name='Tipo de cliente')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la editorial')),
                ('pais', models.CharField(max_length=50, verbose_name='País de origen')),
                ('fundacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Editorial activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del libro')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil')], max_length=3, verbose_name='Género')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_Libreria.autor', verbose_name='Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_Libreria.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de la venta')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completada'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta')], default='PEN', max_length=3, verbose_name='Estado de la venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Libreria.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='app_Libreria.libro', verbose_name='Libro')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Libreria.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
